### ISSUE TITLE
Fix empty configuration and put back `should fail when given no configuration key in the request body`

### ISSUE THREAD

**Issue by Totoketchup** [craft-ai/craft-ai-client-python#185]
Test `should fail when given no configuration key in the request body` has been commented until the empty configuration problem is solved.
Put is back once it has been done.

**Comment by rmdh** [comment]
@Totoketchup do you have a link to the problem/fix this depends on?

**Comment by Giska** [comment]
Close by https://github.com/craft-ai/craft-ai-client-python/pull/196
