### ISSUE TITLE
craft_ai.pandas depends on IPython - Unnecessary dependency

### ISSUE THREAD

**Issue by sperretcraft** [craft-ai/craft-ai-client-python#200]
Hi guys,

I cannot use the `craft_ai.pandas` without `IPython` because the `craft_ai.pandas.utils` import it at the module level, only to use it in the `display_tree` method.

IPython is a very large dependency. I don't want it in my production setup.

Pandas has a way to deal with optional dependencies :
[https://github.com/pandas-dev/pandas/blob/v1.0.5/pandas/compat/_optional.py](https://github.com/pandas-dev/pandas/blob/v1.0.5/pandas/compat/_optional.py)
[https://github.com/pandas-dev/pandas/blob/v1.0.5/pandas/io/excel/_xlrd.py](https://github.com/pandas-dev/pandas/blob/v1.0.5/pandas/io/excel/_xlrd.py)

:rocket: :rocket: :rocket:

**Comment by Giska** [comment]
Closed by https://github.com/craft-ai/craft-ai-client-python/pull/201
