### ISSUE TITLE
The returned message for `add_operations` doesn't retrieve the good operation count

### ISSUE THREAD

**Issue by cloderic** [craft-ai/craft-ai-client-python#62]
... When several chunks are sent the returned message is the one of the last requests the mentioned number is different than the number of actually sent operations (over several chunks)

e.g. you can have the following

![screenshot](https://cloud.githubusercontent.com/assets/958596/25191858/4abe1ca0-2531-11e7-9a9e-913b01c378e6.png)

**Comment by alexisfontaine** [comment]
Those messages are coming from the craft ai server. Do we really want to handle merging the messages in the Python client? The result of the `add_operations` is not documented anywhere and the JavaScript client doesn't return anything.

**Comment by cloderic** [comment]
> Those messages are coming from the craft ai server. Do we really want to handle merging the messages in the Python client?

Short to fix so yeah, but basically we should perhaps change the output of all the python client functions.
